/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Errors1 } from '../models/errors1';

/**
 * Creates an instance of Errors
 */
interface Errors {
  errors: Errors1[];
}

export class ErrorsError extends ApiError<Errors> {}
