<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Exceptions;

class ErrorsException extends \YapstoneStagedOnBoardingServicesLib\Exceptions\ApiException
{
    /**
     * @var \YapstoneStagedOnBoardingServicesLib\Models\Errors1[]
     */
    private $errors;

    /**
     * @param string $reason
     * @param \YapstoneStagedOnBoardingServicesLib\Http\HttpRequest $request
     * @param \YapstoneStagedOnBoardingServicesLib\Http\HttpResponse $response
     * @param \YapstoneStagedOnBoardingServicesLib\Models\Errors1[] $errors
     */
    public function __construct(
        string $reason,
        \YapstoneStagedOnBoardingServicesLib\Http\HttpRequest $request,
        \YapstoneStagedOnBoardingServicesLib\Http\HttpResponse $response,
        array $errors
    ) {
        parent::__construct($reason, $request, $response);
        $this->errors = $errors;
    }

    /**
     * Returns Errors.
     *
     * @return \YapstoneStagedOnBoardingServicesLib\Models\Errors1[]
     */
    public function getErrors(): array
    {
        return $this->errors;
    }

    /**
     * Sets Errors.
     *
     * @required
     * @maps errors
     *
     * @param \YapstoneStagedOnBoardingServicesLib\Models\Errors1[] $errors
     */
    public function setErrors(array $errors): void
    {
        $this->errors = $errors;
    }
}
