/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Address {
  /** Address line 1 (Street address/PO Box/Company name). */
  line1?: string;
  /** Address line 2 (Apartment/Suite/Unit/Building). */
  line2?: string;
  line3?: string;
  line4?: string;
  /** City/District/Suburb/Town/Village. */
  city?: string;
  /** State/County/Province/Region. */
  state?: string;
  /** ZIP or postal code */
  postalCode?: string;
  /** ISO 3166-1 alpha-2 or alpha-3 country code. */
  country?: string;
}

export const addressSchema: Schema<Address> = object({
  line1: ['line1', optional(string())],
  line2: ['line2', optional(string())],
  line3: ['line3', optional(string())],
  line4: ['line4', optional(string())],
  city: ['city', optional(string())],
  state: ['state', optional(string())],
  postalCode: ['postalCode', optional(string())],
  country: ['country', optional(string())],
});
