/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AssetTypeEnum
 */
export enum AssetTypeEnum {
  PROPERTY = 'PROPERTY',
}

/**
 * Schema for AssetTypeEnum
 */
export const assetTypeEnumSchema: Schema<AssetTypeEnum> = stringEnum(AssetTypeEnum);
