/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  literal,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { BaseType2 } from './baseType2';
import { capabilitiesSchema } from './capabilities';
import { CorrelationRef, correlationRefSchema } from './correlationRef';
import { parentSchema } from './parent';

export interface Asset extends BaseType2 {
  id?: string;
  created?: string;
  updated?: string;
  correlationRefs?: CorrelationRef[];
  metadata?: Record<string, string>;
}

export const assetSchema: Schema<any> = object({
  id: ['id', optional(string())],
  created: ['created', optional(string())],
  updated: ['updated', optional(string())],
  correlationRefs: [
    'correlationRefs',
    optional(array(lazy(() => correlationRefSchema))),
  ],
  metadata: ['metadata', optional(dict(string()))],
  parent: ['parent', optional(lazy(() => parentSchema))],
  displayName: ['displayName', optional(string())],
  capabilities: ['capabilities', optional(lazy(() => capabilitiesSchema))],
  preferences: ['preferences', optional(unknown())],
  type: ['type', optional(literal('Asset'))],
});
