/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string, unknown } from '../schema';
import { Parent, parentSchema } from './parent';

export interface BaseType {
  type?: string;
  parent?: Parent;
  displayName?: string;
  preferences?: unknown;
}

export const baseTypeSchema: Schema<BaseType> = object({
  type: ['type', optional(string())],
  parent: ['parent', optional(lazy(() => parentSchema))],
  displayName: ['displayName', optional(string())],
  preferences: ['preferences', optional(unknown())],
});
