/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface BusinessRegistration {
  /** Date of the company was created. */
  formationDate?: string;
  /** The country where the business was created. */
  formationCountry?: string;
  /** The state or province where the business was created */
  formationState?: string;
}

export const businessRegistrationSchema: Schema<BusinessRegistration> = object({
  formationDate: ['formationDate', optional(string())],
  formationCountry: ['formationCountry', optional(string())],
  formationState: ['formationState', optional(string())],
});
