<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use Exception;
use stdClass;
use YapstoneStagedOnBoardingServicesLib\ApiHelper;

class BusinessTypeEnum
{
    public const SOLE_PROPRIETOR = 'SOLE_PROPRIETOR';

    public const PARTNERSHIP = 'PARTNERSHIP';

    public const S_CORP = 'S_CORP';

    public const LLC = 'LLC';

    public const CORPORATION = 'CORPORATION';

    private const _ALL_VALUES = [self::SOLE_PROPRIETOR, self::PARTNERSHIP, self::S_CORP, self::LLC, self::CORPORATION];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        ApiHelper::checkValueInEnum($value, self::class, self::_ALL_VALUES);
        return $value;
    }
}
