/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Capability, capabilitySchema } from './capability';

export interface Capabilities {
  granted?: Capability[];
}

export const capabilitiesSchema: Schema<Capabilities> = object({
  granted: ['granted', optional(array(lazy(() => capabilitySchema)))],
});
