/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CapabilityTypeEnum
 */
export enum CapabilityTypeEnum {
  DIRECTDEBIT = 'DIRECT_DEBIT',
}

/**
 * Schema for CapabilityTypeEnum
 */
export const capabilityTypeEnumSchema: Schema<CapabilityTypeEnum> = stringEnum(CapabilityTypeEnum);
