/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface Capability {
  type: string;
}

export const capabilitySchema: Schema<Capability> = object({
  type: ['type', string()],
});
