/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';
import { Type1Enum, type1EnumSchema } from './type1Enum';

/** **Important !** If the value of the `type` parameter is `DIRECT_DEBIT`, the `Consent` model can be extended with [`DirectDebitConsent`]($m/DirectDebitConsent) */
export interface Consent {
  type: Type1Enum;
  timeOfConsent: string;
  version: number;
}

export const consentSchema: Schema<Consent> = object({
  type: ['type', type1EnumSchema],
  timeOfConsent: ['timeOfConsent', string()],
  version: ['version', number()],
});
