/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface CorrelationRef {
  label: string;
  value: string;
}

export const correlationRefSchema: Schema<CorrelationRef> = object({
  label: ['label', string()],
  value: ['value', string()],
});
