/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface CORSPreferences {
  allowedOrigins?: string[];
}

export const cORSPreferencesSchema: Schema<CORSPreferences> = object({
  allowedOrigins: ['allowedOrigins', optional(array(string()))],
});
