<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class CORSPreferences implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $allowedOrigins;

    /**
     * Returns Allowed Origins.
     *
     * @return string[]|null
     */
    public function getAllowedOrigins(): ?array
    {
        return $this->allowedOrigins;
    }

    /**
     * Sets Allowed Origins.
     *
     * @maps allowedOrigins
     *
     * @param string[]|null $allowedOrigins
     */
    public function setAllowedOrigins(?array $allowedOrigins): void
    {
        $this->allowedOrigins = $allowedOrigins;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->allowedOrigins)) {
            $json['allowedOrigins'] = $this->allowedOrigins;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
