/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  CapabilityTypeEnum,
  capabilityTypeEnumSchema,
} from './capabilityTypeEnum';
import { RequiredFields, requiredFieldsSchema } from './requiredFields';

export interface CountrySpecification {
  id?: string;
  defaultCurrency?: string;
  supportedInstrumentTypes?: string[];
  supportedInstrumentCurrencies?: string[];
  supportedCapabilities?: CapabilityTypeEnum[];
  requiredFields?: RequiredFields;
}

export const countrySpecificationSchema: Schema<CountrySpecification> = object({
  id: ['id', optional(string())],
  defaultCurrency: ['defaultCurrency', optional(string())],
  supportedInstrumentTypes: [
    'supportedInstrumentTypes',
    optional(array(string())),
  ],
  supportedInstrumentCurrencies: [
    'supportedInstrumentCurrencies',
    optional(array(string())),
  ],
  supportedCapabilities: [
    'supportedCapabilities',
    optional(array(capabilityTypeEnumSchema)),
  ],
  requiredFields: [
    'requiredFields',
    optional(lazy(() => requiredFieldsSchema)),
  ],
});
