/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface CountrySpecificationRequiredFields {
  required?: string[];
  optional?: string[];
}

export const countrySpecificationRequiredFieldsSchema: Schema<CountrySpecificationRequiredFields> = object(
  {
    required: ['required', optional(array(string()))],
    optional: ['optional', optional(array(string()))],
  }
);
