<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class CountrySpecificationRequiredFields implements \JsonSerializable
{
    /**
     * @var string[]|null
     */
    private $required;

    /**
     * @var string[]|null
     */
    private $optional;

    /**
     * Returns Required.
     *
     * @return string[]|null
     */
    public function getRequired(): ?array
    {
        return $this->required;
    }

    /**
     * Sets Required.
     *
     * @maps required
     *
     * @param string[]|null $required
     */
    public function setRequired(?array $required): void
    {
        $this->required = $required;
    }

    /**
     * Returns Optional.
     *
     * @return string[]|null
     */
    public function getOptional(): ?array
    {
        return $this->optional;
    }

    /**
     * Sets Optional.
     *
     * @maps optional
     *
     * @param string[]|null $optional
     */
    public function setOptional(?array $optional): void
    {
        $this->optional = $optional;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->required)) {
            $json['required'] = $this->required;
        }
        if (isset($this->optional)) {
            $json['optional'] = $this->optional;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
