<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class CustomerOptions implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $performVerification = true;

    /**
     * Returns Perform Verification.
     */
    public function getPerformVerification(): ?bool
    {
        return $this->performVerification;
    }

    /**
     * Sets Perform Verification.
     *
     * @maps performVerification
     */
    public function setPerformVerification(?bool $performVerification): void
    {
        $this->performVerification = $performVerification;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->performVerification)) {
            $json['performVerification'] = $this->performVerification;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
