/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  CustomerSpecification,
  customerSpecificationSchema,
} from './customerSpecification';
import { Meta, metaSchema } from './meta';

export interface CustomerSpecificationPage {
  meta?: Meta;
  results?: CustomerSpecification[];
}

export const customerSpecificationPageSchema: Schema<CustomerSpecificationPage> = object(
  {
    meta: ['meta', optional(lazy(() => metaSchema))],
    results: [
      'results',
      optional(array(lazy(() => customerSpecificationSchema))),
    ],
  }
);
