/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Customer, customerSchema } from './customer';
import { Meta, metaSchema } from './meta';

export interface CustomerPage {
  meta?: Meta;
  results?: Customer[];
}

export const customerPageSchema: Schema<CustomerPage> = object({
  meta: ['meta', optional(lazy(() => metaSchema))],
  results: ['results', optional(array(lazy(() => customerSchema)))],
});
