/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface CustomerOptions {
  performVerification?: boolean;
}

export const customerOptionsSchema: Schema<CustomerOptions> = object({
  performVerification: ['performVerification', optional(boolean())],
});
