/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string, unknown } from '../schema';

export interface DeniedCapability {
  type: string;
  reasons?: string[];
  requiredActions?: unknown[];
}

export const deniedCapabilitySchema: Schema<DeniedCapability> = object({
  type: ['type', string()],
  reasons: ['reasons', optional(array(string()))],
  requiredActions: ['requiredActions', optional(array(unknown()))],
});
