/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';
import { FrequencyEnum, frequencyEnumSchema } from './frequencyEnum';
import { Type1Enum, type1EnumSchema } from './type1Enum';

export interface DirectDebitConsent {
  type: Type1Enum;
  timeOfConsent: string;
  version: number;
  frequency?: FrequencyEnum;
}

export const directDebitConsentSchema: Schema<DirectDebitConsent> = object({
  type: ['type', type1EnumSchema],
  timeOfConsent: ['timeOfConsent', string()],
  version: ['version', number()],
  frequency: ['frequency', optional(frequencyEnumSchema)],
});
