/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { discriminatedObject, Schema } from '../schema';
import { assetSchema, } from './asset';
import { baseTypeSchema, } from './baseType';
import { baseType2Schema, } from './baseType2';
import { createAssetRequestSchema, } from './createAssetRequest';
import {
  createPropertyAssetRequestSchema,,
} from './createPropertyAssetRequest';
import { propertyAssetSchema, } from './propertyAsset';
import { updateAssetRequestSchema, } from './updateAssetRequest';
import {
  updatePropertyAssetRequestSchema,,
} from './updatePropertyAssetRequest';

export const discriminatedBaseTypeSchema: Schema<any> = discriminatedObject(
  'type',
  'type',
  {
    BaseType: baseTypeSchema,
    CreateAssetRequest: createAssetRequestSchema,
    UpdateAssetRequest: updateAssetRequestSchema,
    CreatePropertyAssetRequest: createPropertyAssetRequestSchema,
    UpdatePropertyAssetRequest: updatePropertyAssetRequestSchema,
 },
  'BaseType'
);

export const discriminatedBaseType2Schema: Schema<any> = discriminatedObject(
  'type',
  'type',
  {
    BaseType2: baseType2Schema,
    Asset: assetSchema,
    PropertyAsset: propertyAssetSchema,
 },
  'BaseType2'
);

