/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, dict, lazy, object, optional, Schema, string } from '../schema';
import { CorrelationRef, correlationRefSchema } from './correlationRef';

export interface Entity {
  id?: string;
  created?: string;
  updated?: string;
  correlationRefs?: CorrelationRef[];
  metadata?: Record<string, string>;
}

export const entitySchema: Schema<Entity> = object({
  id: ['id', optional(string())],
  created: ['created', optional(string())],
  updated: ['updated', optional(string())],
  correlationRefs: [
    'correlationRefs',
    optional(array(lazy(() => correlationRefSchema))),
  ],
  metadata: ['metadata', optional(dict(string()))],
});
