/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';
import { EntityStateEnum, entityStateEnumSchema } from './entityStateEnum';

export interface EntityStatusHistory {
  timestamp?: string;
  state?: EntityStateEnum;
  disabledReasons?: string[];
}

export const entityStatusHistorySchema: Schema<EntityStatusHistory> = object({
  timestamp: ['timestamp', optional(string())],
  state: ['state', optional(entityStateEnumSchema)],
  disabledReasons: ['disabledReasons', optional(array(string()))],
});
