<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;
use YapstoneStagedOnBoardingServicesLib\Utils\DateTimeHelper;

class EntityStatusHistory implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $timestamp;

    /**
     * @var string|null
     */
    private $state;

    /**
     * @var string[]|null
     */
    private $disabledReasons;

    /**
     * Returns Timestamp.
     */
    public function getTimestamp(): ?\DateTime
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     *
     * @maps timestamp
     * @factory \YapstoneStagedOnBoardingServicesLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setTimestamp(?\DateTime $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Returns State.
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * Sets State.
     *
     * @maps state
     * @factory \YapstoneStagedOnBoardingServicesLib\Models\EntityStateEnum::checkValue
     */
    public function setState(?string $state): void
    {
        $this->state = $state;
    }

    /**
     * Returns Disabled Reasons.
     *
     * @return string[]|null
     */
    public function getDisabledReasons(): ?array
    {
        return $this->disabledReasons;
    }

    /**
     * Sets Disabled Reasons.
     *
     * @maps disabledReasons
     *
     * @param string[]|null $disabledReasons
     */
    public function setDisabledReasons(?array $disabledReasons): void
    {
        $this->disabledReasons = $disabledReasons;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->timestamp)) {
            $json['timestamp']       = DateTimeHelper::toRfc3339DateTime($this->timestamp);
        }
        if (isset($this->state)) {
            $json['state']           = EntityStateEnum::checkValue($this->state);
        }
        if (isset($this->disabledReasons)) {
            $json['disabledReasons'] = $this->disabledReasons;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
