/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Errors1 {
  errorCode?: string;
  message?: string;
}

export const errors1Schema: Schema<Errors1> = object({
  errorCode: ['errorCode', optional(string())],
  message: ['message', optional(string())],
});
