<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use Exception;
use stdClass;
use YapstoneStagedOnBoardingServicesLib\ApiHelper;

/**
 * The type of the field.
 */
class FieldTypeEnum
{
    public const STRING = 'STRING';

    public const INTEGER = 'INTEGER';

    public const DECIMAL = 'DECIMAL';

    public const BOOLEAN = 'BOOLEAN';

    public const ENUMERATION = 'ENUMERATION';

    public const DURATION = 'DURATION';

    public const DATE_YEAR = 'DATE_YEAR';

    public const DATE_YEAR_MONTH = 'DATE_YEAR_MONTH';

    public const DATE_YEAR_MONTH_DAY = 'DATE_YEAR_MONTH_DAY';

    public const DATE_TIME = 'DATE_TIME';

    private const _ALL_VALUES = [
        self::STRING,
        self::INTEGER,
        self::DECIMAL,
        self::BOOLEAN,
        self::ENUMERATION,
        self::DURATION,
        self::DATE_YEAR,
        self::DATE_YEAR_MONTH,
        self::DATE_YEAR_MONTH_DAY,
        self::DATE_TIME,
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        ApiHelper::checkValueInEnum($value, self::class, self::_ALL_VALUES);
        return $value;
    }
}
