/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for FieldTypeEnum
 */
export enum FieldTypeEnum {
  STRING = 'STRING',
  INTEGER = 'INTEGER',
  DECIMAL = 'DECIMAL',
  BOOLEAN = 'BOOLEAN',
  ENUMERATION = 'ENUMERATION',
  DURATION = 'DURATION',
  DATEYEAR = 'DATE_YEAR',
  DATEYEARMONTH = 'DATE_YEAR_MONTH',
  DATEYEARMONTHDAY = 'DATE_YEAR_MONTH_DAY',
  DATETIME = 'DATE_TIME',
}

/**
 * Schema for FieldTypeEnum
 */
export const fieldTypeEnumSchema: Schema<FieldTypeEnum> = stringEnum(FieldTypeEnum);
