/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Fingerprint {
  type?: string;
  value?: string;
}

export const fingerprintSchema: Schema<Fingerprint> = object({
  type: ['type', optional(string())],
  value: ['value', optional(string())],
});
