/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

export interface FingerprintSpecification {
  type?: string;
  fields?: string[];
}

export const fingerprintSpecificationSchema: Schema<FingerprintSpecification> = object(
  {
    type: ['type', optional(string())],
    fields: ['fields', optional(array(string()))],
  }
);
