/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GenderEnum
 */
export enum GenderEnum {
  FEMALE = 'FEMALE',
  MALE = 'MALE',
  OTHER = 'OTHER',
}

/**
 * Schema for GenderEnum
 */
export const genderEnumSchema: Schema<GenderEnum> = stringEnum(GenderEnum);
