/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  IdentityDocumentSpecification,
  identityDocumentSpecificationSchema,
} from './identityDocumentSpecification';
import { Meta, metaSchema } from './meta';

export interface IdentityDocumentSpecificationPage {
  meta?: Meta;
  results?: IdentityDocumentSpecification[];
}

export const identityDocumentSpecificationPageSchema: Schema<IdentityDocumentSpecificationPage> = object(
  {
    meta: ['meta', optional(lazy(() => metaSchema))],
    results: [
      'results',
      optional(array(lazy(() => identityDocumentSpecificationSchema))),
    ],
  }
);
