/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  FieldSpecification,
  fieldSpecificationSchema,
} from './fieldSpecification';
import {
  FingerprintSpecification,
  fingerprintSpecificationSchema,
} from './fingerprintSpecification';
import {
  LegalEntityTypeEnum,
  legalEntityTypeEnumSchema,
} from './legalEntityTypeEnum';

export interface IdentityDocumentSpecification {
  name?: string;
  displayName?: string;
  types?: LegalEntityTypeEnum[];
  supportedCountries?: string[];
  details?: FieldSpecification[];
  fingerprints?: FingerprintSpecification[];
}

export const identityDocumentSpecificationSchema: Schema<IdentityDocumentSpecification> = object(
  {
    name: ['name', optional(string())],
    displayName: ['displayName', optional(string())],
    types: ['types', optional(array(legalEntityTypeEnumSchema))],
    supportedCountries: ['supportedCountries', optional(array(string()))],
    details: ['details', optional(array(lazy(() => fieldSpecificationSchema)))],
    fingerprints: [
      'fingerprints',
      optional(array(lazy(() => fingerprintSpecificationSchema))),
    ],
  }
);
