<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class IdentityDocument implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $displayText;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var array<string,string>|null
     */
    private $details;

    /**
     * @var Fingerprint[]|null
     */
    private $fingerprints;

    /**
     * Returns Display Text.
     */
    public function getDisplayText(): ?string
    {
        return $this->displayText;
    }

    /**
     * Sets Display Text.
     *
     * @maps displayText
     */
    public function setDisplayText(?string $displayText): void
    {
        $this->displayText = $displayText;
    }

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Details.
     *
     * @return array<string,string>|null
     */
    public function getDetails(): ?array
    {
        return $this->details;
    }

    /**
     * Sets Details.
     *
     * @maps details
     *
     * @param array<string,string>|null $details
     */
    public function setDetails(?array $details): void
    {
        $this->details = $details;
    }

    /**
     * Returns Fingerprints.
     *
     * @return Fingerprint[]|null
     */
    public function getFingerprints(): ?array
    {
        return $this->fingerprints;
    }

    /**
     * Sets Fingerprints.
     *
     * @maps fingerprints
     *
     * @param Fingerprint[]|null $fingerprints
     */
    public function setFingerprints(?array $fingerprints): void
    {
        $this->fingerprints = $fingerprints;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->displayText)) {
            $json['displayText']  = $this->displayText;
        }
        if (isset($this->type)) {
            $json['type']         = $this->type;
        }
        if (isset($this->details)) {
            $json['details']      = $this->details;
        }
        if (isset($this->fingerprints)) {
            $json['fingerprints'] = $this->fingerprints;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
