/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, dict, lazy, object, optional, Schema, string } from '../schema';
import { Fingerprint, fingerprintSchema } from './fingerprint';

export interface IdentityDocument {
  displayText?: string;
  type?: string;
  details?: Record<string, string>;
  fingerprints?: Fingerprint[];
}

export const identityDocumentSchema: Schema<IdentityDocument> = object({
  displayText: ['displayText', optional(string())],
  type: ['type', optional(string())],
  details: ['details', optional(dict(string()))],
  fingerprints: [
    'fingerprints',
    optional(array(lazy(() => fingerprintSchema))),
  ],
});
