/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The name of the person. It will consist of first, middle, last, additionalLast, honorificPrefix, and honorificSuffix. */
export interface IndividualName {
  /** The persons title. */
  honorificPrefix?: string;
  /** The persons first name. */
  first: string;
  /** The persons middle name or initial. */
  middle?: string;
  /** The persons last name. */
  last: string;
  /** The 2nd last name of the person. */
  additionalLast?: string;
  /** The persons title. */
  honorificSuffix?: string;
}

export const individualNameSchema: Schema<IndividualName> = object({
  honorificPrefix: ['honorificPrefix', optional(string())],
  first: ['first', string()],
  middle: ['middle', optional(string())],
  last: ['last', string()],
  additionalLast: ['additionalLast', optional(string())],
  honorificSuffix: ['honorificSuffix', optional(string())],
});
