/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, dict, lazy, object, optional, Schema, string } from '../schema';
import { Address, addressSchema } from './address';
import { GenderEnum, genderEnumSchema } from './genderEnum';
import { IdentityDocument, identityDocumentSchema } from './identityDocument';
import { IndividualName, individualNameSchema } from './individualName';
import {
  LegalEntityTypeEnum,
  legalEntityTypeEnumSchema,
} from './legalEntityTypeEnum';
import { Phone, phoneSchema } from './phone';
import { SocialNetwork, socialNetworkSchema } from './socialNetwork';

export interface IndividualLegalEntity {
  /** The Party ID of the Customer, for internal use only. Should not appear in user facing documentation. */
  id?: string;
  /** the second description of type parameter */
  type: LegalEntityTypeEnum;
  address?: Address;
  phone?: Phone;
  /** The email address. */
  email?: string;
  /** The website hostname. */
  website?: string;
  socialNetworks?: SocialNetwork[];
  digitalCurrencyAddresses?: string[];
  additional?: Record<string, string>;
  /** The name of the person. It will consist of first, middle, last, additionalLast, honorificPrefix, and honorificSuffix. */
  name?: IndividualName;
  gender?: GenderEnum;
  dateOfBirth?: string;
  /** The country of birth for the person. */
  countryOfBirth?: string;
  /** The nationality of the person. */
  nationality?: string;
  identificationDocuments?: IdentityDocument[];
}

export const individualLegalEntitySchema: Schema<IndividualLegalEntity> = object(
  {
    id: ['id', optional(string())],
    type: ['type', legalEntityTypeEnumSchema],
    address: ['address', optional(lazy(() => addressSchema))],
    phone: ['phone', optional(lazy(() => phoneSchema))],
    email: ['email', optional(string())],
    website: ['website', optional(string())],
    socialNetworks: [
      'socialNetworks',
      optional(array(lazy(() => socialNetworkSchema))),
    ],
    digitalCurrencyAddresses: [
      'digitalCurrencyAddresses',
      optional(array(string())),
    ],
    additional: ['additional', optional(dict(string()))],
    name: ['name', optional(lazy(() => individualNameSchema))],
    gender: ['gender', optional(genderEnumSchema)],
    dateOfBirth: ['dateOfBirth', optional(string())],
    countryOfBirth: ['countryOfBirth', optional(string())],
    nationality: ['nationality', optional(string())],
    identificationDocuments: [
      'identificationDocuments',
      optional(array(lazy(() => identityDocumentSchema))),
    ],
  }
);
