/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema';

export interface InstrumentOptions {
  performVerification?: boolean;
}

export const instrumentOptionsSchema: Schema<InstrumentOptions> = object({
  performVerification: ['performVerification', optional(boolean())],
});
