<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;
use YapstoneStagedOnBoardingServicesLib\Utils\DateTimeHelper;

class Instrument implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $id;

    /**
     * @var \DateTime|null
     */
    private $created;

    /**
     * @var \DateTime|null
     */
    private $updated;

    /**
     * @var CorrelationRef[]|null
     */
    private $correlationRefs;

    /**
     * @var array<string,string>|null
     */
    private $metadata;

    /**
     * @var Parent|null
     */
    private $parent;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var string|null
     */
    private $currency;

    /**
     * @var string|null
     */
    private $country;

    /**
     * @var string|null
     */
    private $displayName;

    /**
     * @var NameOnAccount[]|null
     */
    private $namesOnAccount;

    /**
     * @var Address|null
     */
    private $address;

    /**
     * @var array<string,string>|null
     */
    private $details;

    /**
     * @var Fingerprint[]|null
     */
    private $fingerprints;

    /**
     * @var InstrumentStatus|null
     */
    private $status;

    /**
     * @var Capabilities|null
     */
    private $capabilities;

    /**
     * Returns Id.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Created.
     */
    public function getCreated(): ?\DateTime
    {
        return $this->created;
    }

    /**
     * Sets Created.
     *
     * @maps created
     * @factory \YapstoneStagedOnBoardingServicesLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCreated(?\DateTime $created): void
    {
        $this->created = $created;
    }

    /**
     * Returns Updated.
     */
    public function getUpdated(): ?\DateTime
    {
        return $this->updated;
    }

    /**
     * Sets Updated.
     *
     * @maps updated
     * @factory \YapstoneStagedOnBoardingServicesLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setUpdated(?\DateTime $updated): void
    {
        $this->updated = $updated;
    }

    /**
     * Returns Correlation Refs.
     *
     * @return CorrelationRef[]|null
     */
    public function getCorrelationRefs(): ?array
    {
        return $this->correlationRefs;
    }

    /**
     * Sets Correlation Refs.
     *
     * @maps correlationRefs
     *
     * @param CorrelationRef[]|null $correlationRefs
     */
    public function setCorrelationRefs(?array $correlationRefs): void
    {
        $this->correlationRefs = $correlationRefs;
    }

    /**
     * Returns Metadata.
     *
     * @return array<string,string>|null
     */
    public function getMetadata(): ?array
    {
        return $this->metadata;
    }

    /**
     * Sets Metadata.
     *
     * @maps metadata
     *
     * @param array<string,string>|null $metadata
     */
    public function setMetadata(?array $metadata): void
    {
        $this->metadata = $metadata;
    }

    /**
     * Returns Parent.
     */
    public function getParent(): ?Parent
    {
        return $this->parent;
    }

    /**
     * Sets Parent.
     *
     * @maps parent
     */
    public function setParent(?Parent $parent): void
    {
        $this->parent = $parent;
    }

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Currency.
     */
    public function getCurrency(): ?string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     *
     * @maps currency
     */
    public function setCurrency(?string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Country.
     * ISO 3166-1 alpha-2 or alpha-3 country code.
     */
    public function getCountry(): ?string
    {
        return $this->country;
    }

    /**
     * Sets Country.
     * ISO 3166-1 alpha-2 or alpha-3 country code.
     *
     * @maps country
     */
    public function setCountry(?string $country): void
    {
        $this->country = $country;
    }

    /**
     * Returns Display Name.
     */
    public function getDisplayName(): ?string
    {
        return $this->displayName;
    }

    /**
     * Sets Display Name.
     *
     * @maps displayName
     */
    public function setDisplayName(?string $displayName): void
    {
        $this->displayName = $displayName;
    }

    /**
     * Returns Names on Account.
     *
     * @return NameOnAccount[]|null
     */
    public function getNamesOnAccount(): ?array
    {
        return $this->namesOnAccount;
    }

    /**
     * Sets Names on Account.
     *
     * @maps namesOnAccount
     *
     * @param NameOnAccount[]|null $namesOnAccount
     */
    public function setNamesOnAccount(?array $namesOnAccount): void
    {
        $this->namesOnAccount = $namesOnAccount;
    }

    /**
     * Returns Address.
     */
    public function getAddress(): ?Address
    {
        return $this->address;
    }

    /**
     * Sets Address.
     *
     * @maps address
     */
    public function setAddress(?Address $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Details.
     *
     * @return array<string,string>|null
     */
    public function getDetails(): ?array
    {
        return $this->details;
    }

    /**
     * Sets Details.
     *
     * @maps details
     *
     * @param array<string,string>|null $details
     */
    public function setDetails(?array $details): void
    {
        $this->details = $details;
    }

    /**
     * Returns Fingerprints.
     *
     * @return Fingerprint[]|null
     */
    public function getFingerprints(): ?array
    {
        return $this->fingerprints;
    }

    /**
     * Sets Fingerprints.
     *
     * @maps fingerprints
     *
     * @param Fingerprint[]|null $fingerprints
     */
    public function setFingerprints(?array $fingerprints): void
    {
        $this->fingerprints = $fingerprints;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?InstrumentStatus
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?InstrumentStatus $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Capabilities.
     */
    public function getCapabilities(): ?Capabilities
    {
        return $this->capabilities;
    }

    /**
     * Sets Capabilities.
     *
     * @maps capabilities
     */
    public function setCapabilities(?Capabilities $capabilities): void
    {
        $this->capabilities = $capabilities;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->id)) {
            $json['id']              = $this->id;
        }
        if (isset($this->created)) {
            $json['created']         = DateTimeHelper::toRfc3339DateTime($this->created);
        }
        if (isset($this->updated)) {
            $json['updated']         = DateTimeHelper::toRfc3339DateTime($this->updated);
        }
        if (isset($this->correlationRefs)) {
            $json['correlationRefs'] = $this->correlationRefs;
        }
        if (isset($this->metadata)) {
            $json['metadata']        = $this->metadata;
        }
        if (isset($this->parent)) {
            $json['parent']          = $this->parent;
        }
        if (isset($this->type)) {
            $json['type']            = $this->type;
        }
        if (isset($this->currency)) {
            $json['currency']        = $this->currency;
        }
        if (isset($this->country)) {
            $json['country']         = $this->country;
        }
        if (isset($this->displayName)) {
            $json['displayName']     = $this->displayName;
        }
        if (isset($this->namesOnAccount)) {
            $json['namesOnAccount']  = $this->namesOnAccount;
        }
        if (isset($this->address)) {
            $json['address']         = $this->address;
        }
        if (isset($this->details)) {
            $json['details']         = $this->details;
        }
        if (isset($this->fingerprints)) {
            $json['fingerprints']    = $this->fingerprints;
        }
        if (isset($this->status)) {
            $json['status']          = $this->status;
        }
        if (isset($this->capabilities)) {
            $json['capabilities']    = $this->capabilities;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
