/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InstrumentUsageEnum
 */
export enum InstrumentUsageEnum {
  REUSABLE = 'REUSABLE',
  ONETIME = 'ONE_TIME',
  CONSUMED = 'CONSUMED',
}

/**
 * Schema for InstrumentUsageEnum
 */
export const instrumentUsageEnumSchema: Schema<InstrumentUsageEnum> = stringEnum(InstrumentUsageEnum);
