/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  InstrumentSpecification,
  instrumentSpecificationSchema,
} from './instrumentSpecification';
import { Meta, metaSchema } from './meta';

export interface InstrumentSpecificationPage {
  meta?: Meta;
  results?: InstrumentSpecification[];
}

export const instrumentSpecificationPageSchema: Schema<InstrumentSpecificationPage> = object(
  {
    meta: ['meta', optional(lazy(() => metaSchema))],
    results: [
      'results',
      optional(array(lazy(() => instrumentSpecificationSchema))),
    ],
  }
);
