/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  FieldSpecification,
  fieldSpecificationSchema,
} from './fieldSpecification';
import {
  FingerprintSpecification,
  fingerprintSpecificationSchema,
} from './fingerprintSpecification';

export interface InstrumentSpecification {
  name?: string;
  displayName?: string;
  /** ISO 3166-1 alpha-2 or alpha-3 country codes. */
  supportedCountries?: string[];
  supportedCurrencies?: string[];
  requiredFields?: string[];
  details?: FieldSpecification[];
  fingerprints?: FingerprintSpecification[];
}

export const instrumentSpecificationSchema: Schema<InstrumentSpecification> = object(
  {
    name: ['name', optional(string())],
    displayName: ['displayName', optional(string())],
    supportedCountries: ['supportedCountries', optional(array(string()))],
    supportedCurrencies: ['supportedCurrencies', optional(array(string()))],
    requiredFields: ['requiredFields', optional(array(string()))],
    details: ['details', optional(array(lazy(() => fieldSpecificationSchema)))],
    fingerprints: [
      'fingerprints',
      optional(array(lazy(() => fingerprintSpecificationSchema))),
    ],
  }
);
