/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Instrument, instrumentSchema } from './instrument';
import { Meta, metaSchema } from './meta';

export interface InstrumentPage {
  meta?: Meta;
  results?: Instrument[];
}

export const instrumentPageSchema: Schema<InstrumentPage> = object({
  meta: ['meta', optional(lazy(() => metaSchema))],
  results: ['results', optional(array(lazy(() => instrumentSchema)))],
});
