/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  MarketplaceCORSPreferences,
  marketplaceCORSPreferencesSchema,
} from './marketplaceCORSPreferences';
import {
  NetworkPreferences,
  networkPreferencesSchema,
} from './networkPreferences';
import {
  WebhookPreferences,
  webhookPreferencesSchema,
} from './webhookPreferences';

export interface MarketplacePreferences {
  network?: NetworkPreferences;
  webhook?: WebhookPreferences;
  cors?: MarketplaceCORSPreferences;
}

export const marketplacePreferencesSchema: Schema<MarketplacePreferences> = object(
  {
    network: ['network', optional(lazy(() => networkPreferencesSchema))],
    webhook: ['webhook', optional(lazy(() => webhookPreferencesSchema))],
    cors: ['cors', optional(lazy(() => marketplaceCORSPreferencesSchema))],
  }
);
