/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, dict, lazy, object, optional, Schema, string } from '../schema';
import { Capabilities, capabilitiesSchema } from './capabilities';
import { CorrelationRef, correlationRefSchema } from './correlationRef';
import { LegalEntity, legalEntitySchema } from './legalEntity';
import {
  MarketplacePreferences,
  marketplacePreferencesSchema,
} from './marketplacePreferences';
import { Parent, parentSchema } from './parent';

export interface Marketplace {
  id?: string;
  created?: string;
  updated?: string;
  correlationRefs?: CorrelationRef[];
  metadata?: Record<string, string>;
  parent?: Parent;
  displayName?: string;
  country?: string;
  timezone?: string;
  defaultCurrency?: string;
  defaultLanguage?: string;
  /** **Important !** Depending on the value of the `type` parameter, the `LegalEntity` model is extended with either [`IndividualLegalEntity`]($m/IndividualLegalEntity) or [`BusinessLegalEntity`]($m/BusinessLegalEntity) */
  legalEntity?: LegalEntity;
  preferences?: MarketplacePreferences;
  capabilities?: Capabilities;
}

export const marketplaceSchema: Schema<Marketplace> = object({
  id: ['id', optional(string())],
  created: ['created', optional(string())],
  updated: ['updated', optional(string())],
  correlationRefs: [
    'correlationRefs',
    optional(array(lazy(() => correlationRefSchema))),
  ],
  metadata: ['metadata', optional(dict(string()))],
  parent: ['parent', optional(lazy(() => parentSchema))],
  displayName: ['displayName', optional(string())],
  country: ['country', optional(string())],
  timezone: ['timezone', optional(string())],
  defaultCurrency: ['defaultCurrency', optional(string())],
  defaultLanguage: ['defaultLanguage', optional(string())],
  legalEntity: ['legalEntity', optional(lazy(() => legalEntitySchema))],
  preferences: [
    'preferences',
    optional(lazy(() => marketplacePreferencesSchema)),
  ],
  capabilities: ['capabilities', optional(lazy(() => capabilitiesSchema))],
});
