<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class MarketplaceCORSPreferences implements \JsonSerializable
{
    /**
     * @var CORSPreferences|null
     */
    private $onboarding;

    /**
     * Returns Onboarding.
     */
    public function getOnboarding(): ?CORSPreferences
    {
        return $this->onboarding;
    }

    /**
     * Sets Onboarding.
     *
     * @maps onboarding
     */
    public function setOnboarding(?CORSPreferences $onboarding): void
    {
        $this->onboarding = $onboarding;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->onboarding)) {
            $json['onboarding'] = $this->onboarding;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
