/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { CORSPreferences, cORSPreferencesSchema } from './cORSPreferences';

export interface MarketplaceCORSPreferences {
  onboarding?: CORSPreferences;
}

export const marketplaceCORSPreferencesSchema: Schema<MarketplaceCORSPreferences> = object(
  { onboarding: ['onboarding', optional(lazy(() => cORSPreferencesSchema))] }
);
