<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class MarketplacePreferences implements \JsonSerializable
{
    /**
     * @var NetworkPreferences|null
     */
    private $network;

    /**
     * @var WebhookPreferences|null
     */
    private $webhook;

    /**
     * @var MarketplaceCORSPreferences|null
     */
    private $cors;

    /**
     * Returns Network.
     */
    public function getNetwork(): ?NetworkPreferences
    {
        return $this->network;
    }

    /**
     * Sets Network.
     *
     * @maps network
     */
    public function setNetwork(?NetworkPreferences $network): void
    {
        $this->network = $network;
    }

    /**
     * Returns Webhook.
     */
    public function getWebhook(): ?WebhookPreferences
    {
        return $this->webhook;
    }

    /**
     * Sets Webhook.
     *
     * @maps webhook
     */
    public function setWebhook(?WebhookPreferences $webhook): void
    {
        $this->webhook = $webhook;
    }

    /**
     * Returns Cors.
     */
    public function getCors(): ?MarketplaceCORSPreferences
    {
        return $this->cors;
    }

    /**
     * Sets Cors.
     *
     * @maps cors
     */
    public function setCors(?MarketplaceCORSPreferences $cors): void
    {
        $this->cors = $cors;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->network)) {
            $json['network'] = $this->network;
        }
        if (isset($this->webhook)) {
            $json['webhook'] = $this->webhook;
        }
        if (isset($this->cors)) {
            $json['cors']    = $this->cors;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
