/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema';
import { Money, moneySchema } from './money';
import { PeriodEnum, periodEnumSchema } from './periodEnum';

export interface MerchantVolumeProjection {
  period: PeriodEnum;
  amount: Money;
}

export const merchantVolumeProjectionSchema: Schema<MerchantVolumeProjection> = object(
  {
    period: ['period', periodEnumSchema],
    amount: ['amount', lazy(() => moneySchema)],
  }
);
