<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class MerchantVolumeProjection implements \JsonSerializable
{
    /**
     * @var string
     */
    private $period;

    /**
     * @var Money
     */
    private $amount;

    /**
     * @param string $period
     * @param Money $amount
     */
    public function __construct(string $period, Money $amount)
    {
        $this->period = $period;
        $this->amount = $amount;
    }

    /**
     * Returns Period.
     */
    public function getPeriod(): string
    {
        return $this->period;
    }

    /**
     * Sets Period.
     *
     * @required
     * @maps period
     * @factory \YapstoneStagedOnBoardingServicesLib\Models\PeriodEnum::checkValue
     */
    public function setPeriod(string $period): void
    {
        $this->period = $period;
    }

    /**
     * Returns Amount.
     */
    public function getAmount(): Money
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     *
     * @required
     * @maps amount
     */
    public function setAmount(Money $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['period'] = PeriodEnum::checkValue($this->period);
        $json['amount'] = $this->amount;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
