/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Merchant, merchantSchema } from './merchant';
import { Meta, metaSchema } from './meta';

export interface MerchantPage {
  meta?: Meta;
  results?: Merchant[];
}

export const merchantPageSchema: Schema<MerchantPage> = object({
  meta: ['meta', optional(lazy(() => metaSchema))],
  results: ['results', optional(array(lazy(() => merchantSchema)))],
});
