/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MerchantTypeEnum
 */
export enum MerchantTypeEnum {
  MERCHANT = 'MERCHANT',
  SUBMERCHANT = 'SUB_MERCHANT',
}

/**
 * Schema for MerchantTypeEnum
 */
export const merchantTypeEnumSchema: Schema<MerchantTypeEnum> = stringEnum(MerchantTypeEnum);
