/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  NetworkPreferences,
  networkPreferencesSchema,
} from './networkPreferences';

export interface MerchantPreferences {
  network?: NetworkPreferences;
}

export const merchantPreferencesSchema: Schema<MerchantPreferences> = object({
  network: ['network', optional(lazy(() => networkPreferencesSchema))],
});
