/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema } from '../schema';

export interface Meta {
  offset?: bigint;
  size?: bigint;
}

export const metaSchema: Schema<Meta> = object({
  offset: ['offset', optional(bigint())],
  size: ['size', optional(bigint())],
});
