<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class Meta implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $offset;

    /**
     * @var int|null
     */
    private $size;

    /**
     * Returns Offset.
     */
    public function getOffset(): ?int
    {
        return $this->offset;
    }

    /**
     * Sets Offset.
     *
     * @maps offset
     */
    public function setOffset(?int $offset): void
    {
        $this->offset = $offset;
    }

    /**
     * Returns Size.
     */
    public function getSize(): ?int
    {
        return $this->size;
    }

    /**
     * Sets Size.
     *
     * @maps size
     */
    public function setSize(?int $size): void
    {
        $this->size = $size;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->offset)) {
            $json['offset'] = $this->offset;
        }
        if (isset($this->size)) {
            $json['size']   = $this->size;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
