/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema';

export interface Money {
  currency?: string;
  value?: bigint;
}

export const moneySchema: Schema<Money> = object({
  currency: ['currency', optional(string())],
  value: ['value', optional(bigint())],
});
