/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import {
  LegalEntityTypeEnum,
  legalEntityTypeEnumSchema,
} from './legalEntityTypeEnum';

export interface NameOnAccount {
  /** the second description of type parameter */
  type: LegalEntityTypeEnum;
  name: string;
}

export const nameOnAccountSchema: Schema<NameOnAccount> = object({
  type: ['type', legalEntityTypeEnumSchema],
  name: ['name', string()],
});
