/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface NetworkPreferences {
  merchantCategoryCode?: string;
  merchantIdentifictionNumber?: string;
  gatewayIdentificationNumber?: string;
  terminalIdentificationNumber?: string;
}

export const networkPreferencesSchema: Schema<NetworkPreferences> = object({
  merchantCategoryCode: ['merchantCategoryCode', optional(string())],
  merchantIdentifictionNumber: [
    'merchantIdentifictionNumber',
    optional(string()),
  ],
  gatewayIdentificationNumber: [
    'gatewayIdentificationNumber',
    optional(string()),
  ],
  terminalIdentificationNumber: [
    'terminalIdentificationNumber',
    optional(string()),
  ],
});
