<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class NetworkPreferences implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $merchantCategoryCode;

    /**
     * @var string|null
     */
    private $merchantIdentifictionNumber;

    /**
     * @var string|null
     */
    private $gatewayIdentificationNumber;

    /**
     * @var string|null
     */
    private $terminalIdentificationNumber;

    /**
     * Returns Merchant Category Code.
     */
    public function getMerchantCategoryCode(): ?string
    {
        return $this->merchantCategoryCode;
    }

    /**
     * Sets Merchant Category Code.
     *
     * @maps merchantCategoryCode
     */
    public function setMerchantCategoryCode(?string $merchantCategoryCode): void
    {
        $this->merchantCategoryCode = $merchantCategoryCode;
    }

    /**
     * Returns Merchant Identifiction Number.
     */
    public function getMerchantIdentifictionNumber(): ?string
    {
        return $this->merchantIdentifictionNumber;
    }

    /**
     * Sets Merchant Identifiction Number.
     *
     * @maps merchantIdentifictionNumber
     */
    public function setMerchantIdentifictionNumber(?string $merchantIdentifictionNumber): void
    {
        $this->merchantIdentifictionNumber = $merchantIdentifictionNumber;
    }

    /**
     * Returns Gateway Identification Number.
     */
    public function getGatewayIdentificationNumber(): ?string
    {
        return $this->gatewayIdentificationNumber;
    }

    /**
     * Sets Gateway Identification Number.
     *
     * @maps gatewayIdentificationNumber
     */
    public function setGatewayIdentificationNumber(?string $gatewayIdentificationNumber): void
    {
        $this->gatewayIdentificationNumber = $gatewayIdentificationNumber;
    }

    /**
     * Returns Terminal Identification Number.
     */
    public function getTerminalIdentificationNumber(): ?string
    {
        return $this->terminalIdentificationNumber;
    }

    /**
     * Sets Terminal Identification Number.
     *
     * @maps terminalIdentificationNumber
     */
    public function setTerminalIdentificationNumber(?string $terminalIdentificationNumber): void
    {
        $this->terminalIdentificationNumber = $terminalIdentificationNumber;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->merchantCategoryCode)) {
            $json['merchantCategoryCode']         = $this->merchantCategoryCode;
        }
        if (isset($this->merchantIdentifictionNumber)) {
            $json['merchantIdentifictionNumber']  = $this->merchantIdentifictionNumber;
        }
        if (isset($this->gatewayIdentificationNumber)) {
            $json['gatewayIdentificationNumber']  = $this->gatewayIdentificationNumber;
        }
        if (isset($this->terminalIdentificationNumber)) {
            $json['terminalIdentificationNumber'] = $this->terminalIdentificationNumber;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
