/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Meta, metaSchema } from './meta';

export interface Page {
  meta?: Meta;
}

export const pageSchema: Schema<Page> = object({
  meta: ['meta', optional(lazy(() => metaSchema))],
});
