/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';
import { Type3Enum, type3EnumSchema } from './type3Enum';

export interface Parent {
  type: Type3Enum;
  id: string;
}

export const parentSchema: Schema<Parent> = object({
  type: ['type', type3EnumSchema],
  id: ['id', string()],
});
