/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Meta, metaSchema } from './meta';
import { Payee, payeeSchema } from './payee';

export interface PayeePage {
  meta?: Meta;
  results?: Payee[];
}

export const payeePageSchema: Schema<PayeePage> = object({
  meta: ['meta', optional(lazy(() => metaSchema))],
  results: ['results', optional(array(lazy(() => payeeSchema)))],
});
