/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { CorrelationRef, correlationRefSchema } from './correlationRef';
import { EntityStatus, entityStatusSchema } from './entityStatus';
import { LegalEntity, legalEntitySchema } from './legalEntity';
import { Parent, parentSchema } from './parent';

export interface Payee {
  id?: string;
  created?: string;
  updated?: string;
  correlationRefs?: CorrelationRef[];
  metadata?: Record<string, string>;
  parent?: Parent;
  displayName?: string;
  country?: string;
  timezone?: string;
  defaultCurrency?: string;
  defaultLanguage?: string;
  /** **Important !** Depending on the value of the `type` parameter, the `LegalEntity` model is extended with either [`IndividualLegalEntity`]($m/IndividualLegalEntity) or [`BusinessLegalEntity`]($m/BusinessLegalEntity) */
  legalEntity?: LegalEntity;
  preferences?: unknown;
  status?: EntityStatus;
}

export const payeeSchema: Schema<Payee> = object({
  id: ['id', optional(string())],
  created: ['created', optional(string())],
  updated: ['updated', optional(string())],
  correlationRefs: [
    'correlationRefs',
    optional(array(lazy(() => correlationRefSchema))),
  ],
  metadata: ['metadata', optional(dict(string()))],
  parent: ['parent', optional(lazy(() => parentSchema))],
  displayName: ['displayName', optional(string())],
  country: ['country', optional(string())],
  timezone: ['timezone', optional(string())],
  defaultCurrency: ['defaultCurrency', optional(string())],
  defaultLanguage: ['defaultLanguage', optional(string())],
  legalEntity: ['legalEntity', optional(lazy(() => legalEntitySchema))],
  preferences: ['preferences', optional(unknown())],
  status: ['status', optional(lazy(() => entityStatusSchema))],
});
