/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentTermsEnum
 */
export enum PaymentTermsEnum {
  SINGLECHARGE = 'SINGLE_CHARGE',
  MULTIPLECHARGES = 'MULTIPLE_CHARGES',
}

/**
 * Schema for PaymentTermsEnum
 */
export const paymentTermsEnumSchema: Schema<PaymentTermsEnum> = stringEnum(PaymentTermsEnum);
