/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Meta, metaSchema } from './meta';
import {
  PaymentMethodSpecification,
  paymentMethodSpecificationSchema,
} from './paymentMethodSpecification';

export interface PaymentMethodSpecificationPage {
  meta?: Meta;
  results?: PaymentMethodSpecification[];
}

export const paymentMethodSpecificationPageSchema: Schema<PaymentMethodSpecificationPage> = object(
  {
    meta: ['meta', optional(lazy(() => metaSchema))],
    results: [
      'results',
      optional(array(lazy(() => paymentMethodSpecificationSchema))),
    ],
  }
);
