/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface Phone {
  /** The phone number of the customer. */
  number: string;
  /** The phone extension. */
  extension?: string;
}

export const phoneSchema: Schema<Phone> = object({
  number: ['number', string()],
  extension: ['extension', optional(string())],
});
