<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;
use YapstoneStagedOnBoardingServicesLib\Utils\DateTimeHelper;

class PropertyReservationPolicy implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $checkIn;

    /**
     * @var \DateTime|null
     */
    private $checkOut;

    /**
     * @var int|null
     */
    private $minStayDays;

    /**
     * @var int|null
     */
    private $maxStayDays;

    /**
     * @var string|null
     */
    private $cancellationPolicy;

    /**
     * Returns Check In.
     */
    public function getCheckIn(): ?\DateTime
    {
        return $this->checkIn;
    }

    /**
     * Sets Check In.
     *
     * @maps checkIn
     * @factory \YapstoneStagedOnBoardingServicesLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCheckIn(?\DateTime $checkIn): void
    {
        $this->checkIn = $checkIn;
    }

    /**
     * Returns Check Out.
     */
    public function getCheckOut(): ?\DateTime
    {
        return $this->checkOut;
    }

    /**
     * Sets Check Out.
     *
     * @maps checkOut
     * @factory \YapstoneStagedOnBoardingServicesLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setCheckOut(?\DateTime $checkOut): void
    {
        $this->checkOut = $checkOut;
    }

    /**
     * Returns Min Stay Days.
     */
    public function getMinStayDays(): ?int
    {
        return $this->minStayDays;
    }

    /**
     * Sets Min Stay Days.
     *
     * @maps minStayDays
     */
    public function setMinStayDays(?int $minStayDays): void
    {
        $this->minStayDays = $minStayDays;
    }

    /**
     * Returns Max Stay Days.
     */
    public function getMaxStayDays(): ?int
    {
        return $this->maxStayDays;
    }

    /**
     * Sets Max Stay Days.
     *
     * @maps maxStayDays
     */
    public function setMaxStayDays(?int $maxStayDays): void
    {
        $this->maxStayDays = $maxStayDays;
    }

    /**
     * Returns Cancellation Policy.
     */
    public function getCancellationPolicy(): ?string
    {
        return $this->cancellationPolicy;
    }

    /**
     * Sets Cancellation Policy.
     *
     * @maps cancellationPolicy
     */
    public function setCancellationPolicy(?string $cancellationPolicy): void
    {
        $this->cancellationPolicy = $cancellationPolicy;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->checkIn)) {
            $json['checkIn']            = DateTimeHelper::toRfc3339DateTime($this->checkIn);
        }
        if (isset($this->checkOut)) {
            $json['checkOut']           = DateTimeHelper::toRfc3339DateTime($this->checkOut);
        }
        if (isset($this->minStayDays)) {
            $json['minStayDays']        = $this->minStayDays;
        }
        if (isset($this->maxStayDays)) {
            $json['maxStayDays']        = $this->maxStayDays;
        }
        if (isset($this->cancellationPolicy)) {
            $json['cancellationPolicy'] = $this->cancellationPolicy;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
