/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface PropertyRating {
  /** TODO: figure out what this is! */
  score?: number;
  rating?: number;
  ratingCount?: number;
  inquiryCount?: number;
  complaintCount?: number;
}

export const propertyRatingSchema: Schema<PropertyRating> = object({
  score: ['score', optional(number())],
  rating: ['rating', optional(number())],
  ratingCount: ['ratingCount', optional(number())],
  inquiryCount: ['inquiryCount', optional(number())],
  complaintCount: ['complaintCount', optional(number())],
});
