/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, optional, Schema, string } from '../schema';
import { Money, moneySchema } from './money';

export interface PropertyBookingHistory {
  activeSince?: string;
  chargeCount?: number;
  chargebackCount?: number;
  chargeVolume?: Money;
  chargebackVolume?: Money;
}

export const propertyBookingHistorySchema: Schema<PropertyBookingHistory> = object(
  {
    activeSince: ['activeSince', optional(string())],
    chargeCount: ['chargeCount', optional(number())],
    chargebackCount: ['chargebackCount', optional(number())],
    chargeVolume: ['chargeVolume', optional(lazy(() => moneySchema))],
    chargebackVolume: ['chargebackVolume', optional(lazy(() => moneySchema))],
  }
);
