/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, number, object, optional, Schema, string } from '../schema';

export interface PropertyDetails {
  capacity?: number;
  bedroomCount?: number;
  bathroomCount?: number;
  amenities?: string[];
}

export const propertyDetailsSchema: Schema<PropertyDetails> = object({
  capacity: ['capacity', optional(number())],
  bedroomCount: ['bedroomCount', optional(number())],
  bathroomCount: ['bathroomCount', optional(number())],
  amenities: ['amenities', optional(array(string()))],
});
