/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Meta, metaSchema } from './meta';
import { PropertyAsset, propertyAssetSchema } from './propertyAsset';

export interface PropertyAssetPage {
  meta?: Meta;
  results?: PropertyAsset[];
}

export const propertyAssetPageSchema: Schema<PropertyAssetPage> = object({
  meta: ['meta', optional(lazy(() => metaSchema))],
  results: ['results', optional(array(lazy(() => propertyAssetSchema)))],
});
