<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class PropertyRating implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $score;

    /**
     * @var float|null
     */
    private $rating;

    /**
     * @var int|null
     */
    private $ratingCount;

    /**
     * @var int|null
     */
    private $inquiryCount;

    /**
     * @var int|null
     */
    private $complaintCount;

    /**
     * Returns Score.
     * TODO: figure out what this is!
     */
    public function getScore(): ?float
    {
        return $this->score;
    }

    /**
     * Sets Score.
     * TODO: figure out what this is!
     *
     * @maps score
     */
    public function setScore(?float $score): void
    {
        $this->score = $score;
    }

    /**
     * Returns Rating.
     */
    public function getRating(): ?float
    {
        return $this->rating;
    }

    /**
     * Sets Rating.
     *
     * @maps rating
     */
    public function setRating(?float $rating): void
    {
        $this->rating = $rating;
    }

    /**
     * Returns Rating Count.
     */
    public function getRatingCount(): ?int
    {
        return $this->ratingCount;
    }

    /**
     * Sets Rating Count.
     *
     * @maps ratingCount
     */
    public function setRatingCount(?int $ratingCount): void
    {
        $this->ratingCount = $ratingCount;
    }

    /**
     * Returns Inquiry Count.
     */
    public function getInquiryCount(): ?int
    {
        return $this->inquiryCount;
    }

    /**
     * Sets Inquiry Count.
     *
     * @maps inquiryCount
     */
    public function setInquiryCount(?int $inquiryCount): void
    {
        $this->inquiryCount = $inquiryCount;
    }

    /**
     * Returns Complaint Count.
     */
    public function getComplaintCount(): ?int
    {
        return $this->complaintCount;
    }

    /**
     * Sets Complaint Count.
     *
     * @maps complaintCount
     */
    public function setComplaintCount(?int $complaintCount): void
    {
        $this->complaintCount = $complaintCount;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->score)) {
            $json['score']          = $this->score;
        }
        if (isset($this->rating)) {
            $json['rating']         = $this->rating;
        }
        if (isset($this->ratingCount)) {
            $json['ratingCount']    = $this->ratingCount;
        }
        if (isset($this->inquiryCount)) {
            $json['inquiryCount']   = $this->inquiryCount;
        }
        if (isset($this->complaintCount)) {
            $json['complaintCount'] = $this->complaintCount;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
