<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;
use YapstoneStagedOnBoardingServicesLib\Utils\DateTimeHelper;

class PropertyBookingHistory implements \JsonSerializable
{
    /**
     * @var \DateTime|null
     */
    private $activeSince;

    /**
     * @var int|null
     */
    private $chargeCount;

    /**
     * @var int|null
     */
    private $chargebackCount;

    /**
     * @var Money|null
     */
    private $chargeVolume;

    /**
     * @var Money|null
     */
    private $chargebackVolume;

    /**
     * Returns Active Since.
     */
    public function getActiveSince(): ?\DateTime
    {
        return $this->activeSince;
    }

    /**
     * Sets Active Since.
     *
     * @maps activeSince
     * @factory \YapstoneStagedOnBoardingServicesLib\Utils\DateTimeHelper::fromSimpleDate
     */
    public function setActiveSince(?\DateTime $activeSince): void
    {
        $this->activeSince = $activeSince;
    }

    /**
     * Returns Charge Count.
     */
    public function getChargeCount(): ?int
    {
        return $this->chargeCount;
    }

    /**
     * Sets Charge Count.
     *
     * @maps chargeCount
     */
    public function setChargeCount(?int $chargeCount): void
    {
        $this->chargeCount = $chargeCount;
    }

    /**
     * Returns Chargeback Count.
     */
    public function getChargebackCount(): ?int
    {
        return $this->chargebackCount;
    }

    /**
     * Sets Chargeback Count.
     *
     * @maps chargebackCount
     */
    public function setChargebackCount(?int $chargebackCount): void
    {
        $this->chargebackCount = $chargebackCount;
    }

    /**
     * Returns Charge Volume.
     */
    public function getChargeVolume(): ?Money
    {
        return $this->chargeVolume;
    }

    /**
     * Sets Charge Volume.
     *
     * @maps chargeVolume
     */
    public function setChargeVolume(?Money $chargeVolume): void
    {
        $this->chargeVolume = $chargeVolume;
    }

    /**
     * Returns Chargeback Volume.
     */
    public function getChargebackVolume(): ?Money
    {
        return $this->chargebackVolume;
    }

    /**
     * Sets Chargeback Volume.
     *
     * @maps chargebackVolume
     */
    public function setChargebackVolume(?Money $chargebackVolume): void
    {
        $this->chargebackVolume = $chargebackVolume;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->activeSince)) {
            $json['activeSince']      = DateTimeHelper::toSimpleDate($this->activeSince);
        }
        if (isset($this->chargeCount)) {
            $json['chargeCount']      = $this->chargeCount;
        }
        if (isset($this->chargebackCount)) {
            $json['chargebackCount']  = $this->chargebackCount;
        }
        if (isset($this->chargeVolume)) {
            $json['chargeVolume']     = $this->chargeVolume;
        }
        if (isset($this->chargebackVolume)) {
            $json['chargebackVolume'] = $this->chargebackVolume;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
