<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

/**
 * @discriminator type
 * @discriminatorType PropertyAsset
 */
class PropertyAsset extends Asset implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $name;

    /**
     * @var Address|null
     */
    private $address;

    /**
     * @var PropertyDetails|null
     */
    private $details;

    /**
     * @var PropertyRating|null
     */
    private $rating;

    /**
     * @var PropertyReservationPolicy|null
     */
    private $reservationPolicy;

    /**
     * @var PropertyRateDetails|null
     */
    private $rateDetails;

    /**
     * @var PropertyBookingHistory|null
     */
    private $bookingHistory;

    /**
     * @var EntityStatus|null
     */
    private $status;

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Address.
     */
    public function getAddress(): ?Address
    {
        return $this->address;
    }

    /**
     * Sets Address.
     *
     * @maps address
     */
    public function setAddress(?Address $address): void
    {
        $this->address = $address;
    }

    /**
     * Returns Details.
     */
    public function getDetails(): ?PropertyDetails
    {
        return $this->details;
    }

    /**
     * Sets Details.
     *
     * @maps details
     */
    public function setDetails(?PropertyDetails $details): void
    {
        $this->details = $details;
    }

    /**
     * Returns Rating.
     */
    public function getRating(): ?PropertyRating
    {
        return $this->rating;
    }

    /**
     * Sets Rating.
     *
     * @maps rating
     */
    public function setRating(?PropertyRating $rating): void
    {
        $this->rating = $rating;
    }

    /**
     * Returns Reservation Policy.
     */
    public function getReservationPolicy(): ?PropertyReservationPolicy
    {
        return $this->reservationPolicy;
    }

    /**
     * Sets Reservation Policy.
     *
     * @maps reservationPolicy
     */
    public function setReservationPolicy(?PropertyReservationPolicy $reservationPolicy): void
    {
        $this->reservationPolicy = $reservationPolicy;
    }

    /**
     * Returns Rate Details.
     */
    public function getRateDetails(): ?PropertyRateDetails
    {
        return $this->rateDetails;
    }

    /**
     * Sets Rate Details.
     *
     * @maps rateDetails
     */
    public function setRateDetails(?PropertyRateDetails $rateDetails): void
    {
        $this->rateDetails = $rateDetails;
    }

    /**
     * Returns Booking History.
     */
    public function getBookingHistory(): ?PropertyBookingHistory
    {
        return $this->bookingHistory;
    }

    /**
     * Sets Booking History.
     *
     * @maps bookingHistory
     */
    public function setBookingHistory(?PropertyBookingHistory $bookingHistory): void
    {
        $this->bookingHistory = $bookingHistory;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?EntityStatus
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps status
     */
    public function setStatus(?EntityStatus $status): void
    {
        $this->status = $status;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->name)) {
            $json['name']              = $this->name;
        }
        if (isset($this->address)) {
            $json['address']           = $this->address;
        }
        if (isset($this->details)) {
            $json['details']           = $this->details;
        }
        if (isset($this->rating)) {
            $json['rating']            = $this->rating;
        }
        if (isset($this->reservationPolicy)) {
            $json['reservationPolicy'] = $this->reservationPolicy;
        }
        if (isset($this->rateDetails)) {
            $json['rateDetails']       = $this->rateDetails;
        }
        if (isset($this->bookingHistory)) {
            $json['bookingHistory']    = $this->bookingHistory;
        }
        if (isset($this->status)) {
            $json['status']            = $this->status;
        }
        $json = array_merge($json, parent::jsonSerialize(true));

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
