/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface PropertyReservationPolicy {
  checkIn?: string;
  checkOut?: string;
  minStayDays?: number;
  maxStayDays?: number;
  cancellationPolicy?: string;
}

export const propertyReservationPolicySchema: Schema<PropertyReservationPolicy> = object(
  {
    checkIn: ['checkIn', optional(string())],
    checkOut: ['checkOut', optional(string())],
    minStayDays: ['minStayDays', optional(number())],
    maxStayDays: ['maxStayDays', optional(number())],
    cancellationPolicy: ['cancellationPolicy', optional(string())],
  }
);
