/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema } from '../schema';
import { Money, moneySchema } from './money';
import { PaymentTermsEnum, paymentTermsEnumSchema } from './paymentTermsEnum';
import {
  RentingFrequencyEnum,
  rentingFrequencyEnumSchema,
} from './rentingFrequencyEnum';

export interface PropertyRateDetails {
  min?: Money;
  max?: Money;
  cleaningFee?: Money;
  sameDayChargeAllowed?: boolean;
  autoPricing?: boolean;
  rentingFrequency?: RentingFrequencyEnum;
  paymentTerms?: PaymentTermsEnum;
}

export const propertyRateDetailsSchema: Schema<PropertyRateDetails> = object({
  min: ['min', optional(lazy(() => moneySchema))],
  max: ['max', optional(lazy(() => moneySchema))],
  cleaningFee: ['cleaningFee', optional(lazy(() => moneySchema))],
  sameDayChargeAllowed: ['sameDayChargeAllowed', optional(boolean())],
  autoPricing: ['autoPricing', optional(boolean())],
  rentingFrequency: ['rentingFrequency', optional(rentingFrequencyEnumSchema)],
  paymentTerms: ['paymentTerms', optional(paymentTermsEnumSchema)],
});
