<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class PropertyRateDetails implements \JsonSerializable
{
    /**
     * @var Money|null
     */
    private $min;

    /**
     * @var Money|null
     */
    private $max;

    /**
     * @var Money|null
     */
    private $cleaningFee;

    /**
     * @var bool|null
     */
    private $sameDayChargeAllowed;

    /**
     * @var bool|null
     */
    private $autoPricing;

    /**
     * @var string|null
     */
    private $rentingFrequency;

    /**
     * @var string|null
     */
    private $paymentTerms;

    /**
     * Returns Min.
     */
    public function getMin(): ?Money
    {
        return $this->min;
    }

    /**
     * Sets Min.
     *
     * @maps min
     */
    public function setMin(?Money $min): void
    {
        $this->min = $min;
    }

    /**
     * Returns Max.
     */
    public function getMax(): ?Money
    {
        return $this->max;
    }

    /**
     * Sets Max.
     *
     * @maps max
     */
    public function setMax(?Money $max): void
    {
        $this->max = $max;
    }

    /**
     * Returns Cleaning Fee.
     */
    public function getCleaningFee(): ?Money
    {
        return $this->cleaningFee;
    }

    /**
     * Sets Cleaning Fee.
     *
     * @maps cleaningFee
     */
    public function setCleaningFee(?Money $cleaningFee): void
    {
        $this->cleaningFee = $cleaningFee;
    }

    /**
     * Returns Same Day Charge Allowed.
     */
    public function getSameDayChargeAllowed(): ?bool
    {
        return $this->sameDayChargeAllowed;
    }

    /**
     * Sets Same Day Charge Allowed.
     *
     * @maps sameDayChargeAllowed
     */
    public function setSameDayChargeAllowed(?bool $sameDayChargeAllowed): void
    {
        $this->sameDayChargeAllowed = $sameDayChargeAllowed;
    }

    /**
     * Returns Auto Pricing.
     */
    public function getAutoPricing(): ?bool
    {
        return $this->autoPricing;
    }

    /**
     * Sets Auto Pricing.
     *
     * @maps autoPricing
     */
    public function setAutoPricing(?bool $autoPricing): void
    {
        $this->autoPricing = $autoPricing;
    }

    /**
     * Returns Renting Frequency.
     */
    public function getRentingFrequency(): ?string
    {
        return $this->rentingFrequency;
    }

    /**
     * Sets Renting Frequency.
     *
     * @maps rentingFrequency
     * @factory \YapstoneStagedOnBoardingServicesLib\Models\RentingFrequencyEnum::checkValue
     */
    public function setRentingFrequency(?string $rentingFrequency): void
    {
        $this->rentingFrequency = $rentingFrequency;
    }

    /**
     * Returns Payment Terms.
     */
    public function getPaymentTerms(): ?string
    {
        return $this->paymentTerms;
    }

    /**
     * Sets Payment Terms.
     *
     * @maps paymentTerms
     * @factory \YapstoneStagedOnBoardingServicesLib\Models\PaymentTermsEnum::checkValue
     */
    public function setPaymentTerms(?string $paymentTerms): void
    {
        $this->paymentTerms = $paymentTerms;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->min)) {
            $json['min']                  = $this->min;
        }
        if (isset($this->max)) {
            $json['max']                  = $this->max;
        }
        if (isset($this->cleaningFee)) {
            $json['cleaningFee']          = $this->cleaningFee;
        }
        if (isset($this->sameDayChargeAllowed)) {
            $json['sameDayChargeAllowed'] = $this->sameDayChargeAllowed;
        }
        if (isset($this->autoPricing)) {
            $json['autoPricing']          = $this->autoPricing;
        }
        if (isset($this->rentingFrequency)) {
            $json['rentingFrequency']     = RentingFrequencyEnum::checkValue($this->rentingFrequency);
        }
        if (isset($this->paymentTerms)) {
            $json['paymentTerms']         = PaymentTermsEnum::checkValue($this->paymentTerms);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
