/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RentingFrequencyEnum
 */
export enum RentingFrequencyEnum {
  LESSTHANONEMONTH = 'LESS_THAN_ONE_MONTH',
  ONETOTHREEMONTHS = 'ONE_TO_THREE_MONTHS',
  THREETOSIXMONTHS = 'THREE_TO_SIX_MONTHS',
  SIXORMOREMONTHS = 'SIX_OR_MORE_MONTHS',
}

/**
 * Schema for RentingFrequencyEnum
 */
export const rentingFrequencyEnumSchema: Schema<RentingFrequencyEnum> = stringEnum(RentingFrequencyEnum);
