<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use Exception;
use stdClass;
use YapstoneStagedOnBoardingServicesLib\ApiHelper;

class RentingFrequencyEnum
{
    public const LESS_THAN_ONE_MONTH = 'LESS_THAN_ONE_MONTH';

    public const ONE_TO_THREE_MONTHS = 'ONE_TO_THREE_MONTHS';

    public const THREE_TO_SIX_MONTHS = 'THREE_TO_SIX_MONTHS';

    public const SIX_OR_MORE_MONTHS = 'SIX_OR_MORE_MONTHS';

    private const _ALL_VALUES = [
        self::LESS_THAN_ONE_MONTH,
        self::ONE_TO_THREE_MONTHS,
        self::THREE_TO_SIX_MONTHS,
        self::SIX_OR_MORE_MONTHS,
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        ApiHelper::checkValueInEnum($value, self::class, self::_ALL_VALUES);
        return $value;
    }
}
