/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  CountrySpecificationRequiredFields,
  countrySpecificationRequiredFieldsSchema,
} from './countrySpecificationRequiredFields';

export interface RequiredFields {
  merchant?: CountrySpecificationRequiredFields;
  instrument?: CountrySpecificationRequiredFields;
  customer?: CountrySpecificationRequiredFields;
  property?: CountrySpecificationRequiredFields;
}

export const requiredFieldsSchema: Schema<RequiredFields> = object({
  merchant: [
    'merchant',
    optional(lazy(() => countrySpecificationRequiredFieldsSchema)),
  ],
  instrument: [
    'instrument',
    optional(lazy(() => countrySpecificationRequiredFieldsSchema)),
  ],
  customer: [
    'customer',
    optional(lazy(() => countrySpecificationRequiredFieldsSchema)),
  ],
  property: [
    'property',
    optional(lazy(() => countrySpecificationRequiredFieldsSchema)),
  ],
});
