/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, dict, lazy, object, optional, Schema, string } from '../schema';
import { CorrelationRef, correlationRefSchema } from './correlationRef';

export interface Request {
  correlationRefs?: CorrelationRef[];
  metadata?: Record<string, string>;
}

export const requestSchema: Schema<Request> = object({
  correlationRefs: [
    'correlationRefs',
    optional(array(lazy(() => correlationRefSchema))),
  ],
  metadata: ['metadata', optional(dict(string()))],
});
