<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class RequiredFields implements \JsonSerializable
{
    /**
     * @var CountrySpecificationRequiredFields|null
     */
    private $merchant;

    /**
     * @var CountrySpecificationRequiredFields|null
     */
    private $instrument;

    /**
     * @var CountrySpecificationRequiredFields|null
     */
    private $customer;

    /**
     * @var CountrySpecificationRequiredFields|null
     */
    private $property;

    /**
     * Returns Merchant.
     */
    public function getMerchant(): ?CountrySpecificationRequiredFields
    {
        return $this->merchant;
    }

    /**
     * Sets Merchant.
     *
     * @maps merchant
     */
    public function setMerchant(?CountrySpecificationRequiredFields $merchant): void
    {
        $this->merchant = $merchant;
    }

    /**
     * Returns Instrument.
     */
    public function getInstrument(): ?CountrySpecificationRequiredFields
    {
        return $this->instrument;
    }

    /**
     * Sets Instrument.
     *
     * @maps instrument
     */
    public function setInstrument(?CountrySpecificationRequiredFields $instrument): void
    {
        $this->instrument = $instrument;
    }

    /**
     * Returns Customer.
     */
    public function getCustomer(): ?CountrySpecificationRequiredFields
    {
        return $this->customer;
    }

    /**
     * Sets Customer.
     *
     * @maps customer
     */
    public function setCustomer(?CountrySpecificationRequiredFields $customer): void
    {
        $this->customer = $customer;
    }

    /**
     * Returns Property.
     */
    public function getProperty(): ?CountrySpecificationRequiredFields
    {
        return $this->property;
    }

    /**
     * Sets Property.
     *
     * @maps property
     */
    public function setProperty(?CountrySpecificationRequiredFields $property): void
    {
        $this->property = $property;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->merchant)) {
            $json['merchant']   = $this->merchant;
        }
        if (isset($this->instrument)) {
            $json['instrument'] = $this->instrument;
        }
        if (isset($this->customer)) {
            $json['customer']   = $this->customer;
        }
        if (isset($this->property)) {
            $json['property']   = $this->property;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
