/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, optional, Schema, string } from '../schema';

/** When both `allOf` and `oneOf` are specified they should be considered as expressions in an AND condition. Eg. allOf[X, Y] AND oneOf[A, B]. */
export interface RequiredIdentityDocuments {
  /** A list of acceptable identity documents, of which all specified are required. */
  allOf?: string[];
  /** A list of acceptable identity documents, from which one is required to be chosen. */
  oneOf?: string[];
}

export const requiredIdentityDocumentsSchema: Schema<RequiredIdentityDocuments> = object(
  {
    allOf: ['allOf', optional(array(string()))],
    oneOf: ['oneOf', optional(array(string()))],
  }
);
