/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { RiskDecisionEnum, riskDecisionEnumSchema } from './riskDecisionEnum';
import {
  RiskRequiredAction,
  riskRequiredActionSchema,
} from './riskRequiredAction';

export interface RiskStatusHistory {
  timestamp?: string;
  decision?: RiskDecisionEnum;
  declinedReasons?: string[];
  requiredActions?: RiskRequiredAction[];
}

export const riskStatusHistorySchema: Schema<RiskStatusHistory> = object({
  timestamp: ['timestamp', optional(string())],
  decision: ['decision', optional(riskDecisionEnumSchema)],
  declinedReasons: ['declinedReasons', optional(array(string()))],
  requiredActions: [
    'requiredActions',
    optional(array(lazy(() => riskRequiredActionSchema))),
  ],
});
