<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class RiskStatus implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $decision;

    /**
     * @var string[]|null
     */
    private $declinedReasons;

    /**
     * @var RiskRequiredAction[]|null
     */
    private $requiredActions;

    /**
     * @var RiskStatusHistory[]|null
     */
    private $history;

    /**
     * Returns Decision.
     */
    public function getDecision(): ?string
    {
        return $this->decision;
    }

    /**
     * Sets Decision.
     *
     * @maps decision
     * @factory \YapstoneStagedOnBoardingServicesLib\Models\RiskDecisionEnum::checkValue
     */
    public function setDecision(?string $decision): void
    {
        $this->decision = $decision;
    }

    /**
     * Returns Declined Reasons.
     *
     * @return string[]|null
     */
    public function getDeclinedReasons(): ?array
    {
        return $this->declinedReasons;
    }

    /**
     * Sets Declined Reasons.
     *
     * @maps declinedReasons
     *
     * @param string[]|null $declinedReasons
     */
    public function setDeclinedReasons(?array $declinedReasons): void
    {
        $this->declinedReasons = $declinedReasons;
    }

    /**
     * Returns Required Actions.
     *
     * @return RiskRequiredAction[]|null
     */
    public function getRequiredActions(): ?array
    {
        return $this->requiredActions;
    }

    /**
     * Sets Required Actions.
     *
     * @maps requiredActions
     *
     * @param RiskRequiredAction[]|null $requiredActions
     */
    public function setRequiredActions(?array $requiredActions): void
    {
        $this->requiredActions = $requiredActions;
    }

    /**
     * Returns History.
     *
     * @return RiskStatusHistory[]|null
     */
    public function getHistory(): ?array
    {
        return $this->history;
    }

    /**
     * Sets History.
     *
     * @maps history
     *
     * @param RiskStatusHistory[]|null $history
     */
    public function setHistory(?array $history): void
    {
        $this->history = $history;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->decision)) {
            $json['decision']        = RiskDecisionEnum::checkValue($this->decision);
        }
        if (isset($this->declinedReasons)) {
            $json['declinedReasons'] = $this->declinedReasons;
        }
        if (isset($this->requiredActions)) {
            $json['requiredActions'] = $this->requiredActions;
        }
        if (isset($this->history)) {
            $json['history']         = $this->history;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
