/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for RiskDecisionEnum
 */
export enum RiskDecisionEnum {
  NOTEVALUATED = 'NOT_EVALUATED',
  UNDERREVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  DECLINED = 'DECLINED',
}

/**
 * Schema for RiskDecisionEnum
 */
export const riskDecisionEnumSchema: Schema<RiskDecisionEnum> = stringEnum(RiskDecisionEnum);
