/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Type3Enum
 */
export enum Type3Enum {
  MARKETPLACE = 'MARKETPLACE',
  MERCHANT = 'MERCHANT',
  SUBMERCHANT = 'SUB_MERCHANT',
  CUSTOMER = 'CUSTOMER',
  PAYEE = 'PAYEE',
}

/**
 * Schema for Type3Enum
 */
export const type3EnumSchema: Schema<Type3Enum> = stringEnum(Type3Enum);
