/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TypeEnum
 */
export enum TypeEnum {
  FACEBOOK = 'FACEBOOK',
  TWITTER = 'TWITTER',
  GOOGLEPLUS = 'GOOGLE_PLUS',
  LINKEDIN = 'LINKEDIN',
  PINTEREST = 'PINTEREST',
  INSTAGRAM = 'INSTAGRAM',
  SNAPCHAT = 'SNAPCHAT',
}

/**
 * Schema for TypeEnum
 */
export const typeEnumSchema: Schema<TypeEnum> = stringEnum(TypeEnum);
