<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use Exception;
use stdClass;
use YapstoneStagedOnBoardingServicesLib\ApiHelper;

class TypeEnum
{
    public const FACEBOOK = 'FACEBOOK';

    public const TWITTER = 'TWITTER';

    public const GOOGLE_PLUS = 'GOOGLE_PLUS';

    public const LINKEDIN = 'LINKEDIN';

    public const PINTEREST = 'PINTEREST';

    public const INSTAGRAM = 'INSTAGRAM';

    public const SNAPCHAT = 'SNAPCHAT';

    private const _ALL_VALUES = [
        self::FACEBOOK,
        self::TWITTER,
        self::GOOGLE_PLUS,
        self::LINKEDIN,
        self::PINTEREST,
        self::INSTAGRAM,
        self::SNAPCHAT,
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        ApiHelper::checkValueInEnum($value, self::class, self::_ALL_VALUES);
        return $value;
    }
}
