/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  literal,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { BaseType } from './baseType';
import { CorrelationRef, correlationRefSchema } from './correlationRef';
import { parentSchema } from './parent';

export interface UpdateAssetRequest extends BaseType {
  correlationRefs?: CorrelationRef[];
  metadata?: Record<string, string>;
}

export const updateAssetRequestSchema: Schema<any> = object({
  correlationRefs: [
    'correlationRefs',
    optional(array(lazy(() => correlationRefSchema))),
  ],
  metadata: ['metadata', optional(dict(string()))],
  parent: ['parent', optional(lazy(() => parentSchema))],
  displayName: ['displayName', optional(string())],
  preferences: ['preferences', optional(unknown())],
  type: ['type', optional(literal('UpdateAssetRequest'))],
});
