/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  literal,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { Address, addressSchema } from './address';
import { correlationRefSchema } from './correlationRef';
import { parentSchema } from './parent';
import {
  PropertyBookingHistory,
  propertyBookingHistorySchema,
} from './propertyBookingHistory';
import { PropertyDetails, propertyDetailsSchema } from './propertyDetails';
import {
  PropertyRateDetails,
  propertyRateDetailsSchema,
} from './propertyRateDetails';
import { PropertyRating, propertyRatingSchema } from './propertyRating';
import {
  PropertyReservationPolicy,
  propertyReservationPolicySchema,
} from './propertyReservationPolicy';
import { UpdateAssetRequest } from './updateAssetRequest';

export interface UpdatePropertyAssetRequest extends UpdateAssetRequest {
  name?: string;
  address?: Address;
  details?: PropertyDetails;
  rating?: PropertyRating;
  reservationPolicy?: PropertyReservationPolicy;
  rateDetails?: PropertyRateDetails;
  bookingHistory?: PropertyBookingHistory;
}

export const updatePropertyAssetRequestSchema: Schema<any> = object({
  name: ['name', optional(string())],
  address: ['address', optional(lazy(() => addressSchema))],
  details: ['details', optional(lazy(() => propertyDetailsSchema))],
  rating: ['rating', optional(lazy(() => propertyRatingSchema))],
  reservationPolicy: [
    'reservationPolicy',
    optional(lazy(() => propertyReservationPolicySchema)),
  ],
  rateDetails: ['rateDetails', optional(lazy(() => propertyRateDetailsSchema))],
  bookingHistory: [
    'bookingHistory',
    optional(lazy(() => propertyBookingHistorySchema)),
  ],
  correlationRefs: [
    'correlationRefs',
    optional(array(lazy(() => correlationRefSchema))),
  ],
  metadata: ['metadata', optional(dict(string()))],
  parent: ['parent', optional(lazy(() => parentSchema))],
  displayName: ['displayName', optional(string())],
  preferences: ['preferences', optional(unknown())],
  type: ['type', optional(literal('UpdatePropertyAssetRequest'))],
});
