/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  dict,
  lazy,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';
import { CorrelationRef, correlationRefSchema } from './correlationRef';
import { LegalEntity, legalEntitySchema } from './legalEntity';

export interface UpdatePayeeRequest {
  correlationRefs?: CorrelationRef[];
  metadata?: Record<string, string>;
  displayName?: string;
  country?: string;
  timezone?: string;
  defaultCurrency?: string;
  defaultLanguage?: string;
  /** **Important !** Depending on the value of the `type` parameter, the `LegalEntity` model is extended with either [`IndividualLegalEntity`]($m/IndividualLegalEntity) or [`BusinessLegalEntity`]($m/BusinessLegalEntity) */
  legalEntity?: LegalEntity;
  preferences?: unknown;
}

export const updatePayeeRequestSchema: Schema<UpdatePayeeRequest> = object({
  correlationRefs: [
    'correlationRefs',
    optional(array(lazy(() => correlationRefSchema))),
  ],
  metadata: ['metadata', optional(dict(string()))],
  displayName: ['displayName', optional(string())],
  country: ['country', optional(string())],
  timezone: ['timezone', optional(string())],
  defaultCurrency: ['defaultCurrency', optional(string())],
  defaultLanguage: ['defaultLanguage', optional(string())],
  legalEntity: ['legalEntity', optional(lazy(() => legalEntitySchema))],
  preferences: ['preferences', optional(unknown())],
});
