/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { StateEnum, stateEnumSchema } from './stateEnum';
import { ValidationAction, validationActionSchema } from './validationAction';

export interface ValidationStatus {
  state?: StateEnum;
  requiredActions?: ValidationAction[];
}

export const validationStatusSchema: Schema<ValidationStatus> = object({
  state: ['state', optional(stateEnumSchema)],
  requiredActions: [
    'requiredActions',
    optional(array(lazy(() => validationActionSchema))),
  ],
});
