/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface VerificationAction {
  code?: string;
  description?: string;
}

export const verificationActionSchema: Schema<VerificationAction> = object({
  code: ['code', optional(string())],
  description: ['description', optional(string())],
});
