/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { dict, object, optional, Schema, string } from '../schema';

export interface VerifyInstrumentRequest {
  details?: Record<string, string>;
}

export const verifyInstrumentRequestSchema: Schema<VerifyInstrumentRequest> = object(
  { details: ['details', optional(dict(string()))] }
);
