<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class VerificationStatus implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $state;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var VerificationAction[]|null
     */
    private $requiredActions;

    /**
     * @var VerificationStatusHistory[]|null
     */
    private $history;

    /**
     * Returns State.
     */
    public function getState(): ?string
    {
        return $this->state;
    }

    /**
     * Sets State.
     *
     * @maps state
     * @factory \YapstoneStagedOnBoardingServicesLib\Models\VerificationStateEnum::checkValue
     */
    public function setState(?string $state): void
    {
        $this->state = $state;
    }

    /**
     * Returns Description.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Required Actions.
     *
     * @return VerificationAction[]|null
     */
    public function getRequiredActions(): ?array
    {
        return $this->requiredActions;
    }

    /**
     * Sets Required Actions.
     *
     * @maps requiredActions
     *
     * @param VerificationAction[]|null $requiredActions
     */
    public function setRequiredActions(?array $requiredActions): void
    {
        $this->requiredActions = $requiredActions;
    }

    /**
     * Returns History.
     *
     * @return VerificationStatusHistory[]|null
     */
    public function getHistory(): ?array
    {
        return $this->history;
    }

    /**
     * Sets History.
     *
     * @maps history
     *
     * @param VerificationStatusHistory[]|null $history
     */
    public function setHistory(?array $history): void
    {
        $this->history = $history;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->state)) {
            $json['state']           = VerificationStateEnum::checkValue($this->state);
        }
        if (isset($this->description)) {
            $json['description']     = $this->description;
        }
        if (isset($this->requiredActions)) {
            $json['requiredActions'] = $this->requiredActions;
        }
        if (isset($this->history)) {
            $json['history']         = $this->history;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
