/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  VerificationAction,
  verificationActionSchema,
} from './verificationAction';
import {
  VerificationStateEnum,
  verificationStateEnumSchema,
} from './verificationStateEnum';
import {
  VerificationStatusHistory,
  verificationStatusHistorySchema,
} from './verificationStatusHistory';

export interface VerificationStatus {
  state?: VerificationStateEnum;
  description?: string;
  requiredActions?: VerificationAction[];
  history?: VerificationStatusHistory[];
}

export const verificationStatusSchema: Schema<VerificationStatus> = object({
  state: ['state', optional(verificationStateEnumSchema)],
  description: ['description', optional(string())],
  requiredActions: [
    'requiredActions',
    optional(array(lazy(() => verificationActionSchema))),
  ],
  history: [
    'history',
    optional(array(lazy(() => verificationStatusHistorySchema))),
  ],
});
