/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VerificationStateEnum
 */
export enum VerificationStateEnum {
  UNVERIFIED = 'UNVERIFIED',
  INPROGRESS = 'IN_PROGRESS',
  ACTIONREQUIRED = 'ACTION_REQUIRED',
  VERIFIED = 'VERIFIED',
  DECLINED = 'DECLINED',
}

/**
 * Schema for VerificationStateEnum
 */
export const verificationStateEnumSchema: Schema<VerificationStateEnum> = stringEnum(VerificationStateEnum);
