/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import {
  VerificationAction,
  verificationActionSchema,
} from './verificationAction';
import {
  VerificationStateEnum,
  verificationStateEnumSchema,
} from './verificationStateEnum';

export interface VerificationStatusHistory {
  timestamp?: string;
  state?: VerificationStateEnum;
  description?: string;
  requiredActions?: VerificationAction[];
}

export const verificationStatusHistorySchema: Schema<VerificationStatusHistory> = object(
  {
    timestamp: ['timestamp', optional(string())],
    state: ['state', optional(verificationStateEnumSchema)],
    description: ['description', optional(string())],
    requiredActions: [
      'requiredActions',
      optional(array(lazy(() => verificationActionSchema))),
    ],
  }
);
