/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  WebhookAuthenticationPreference,
  webhookAuthenticationPreferenceSchema,
} from './webhookAuthenticationPreference';

export interface WebhookPreferences {
  /** Client supplied URL that will be notified for all onboarding events. */
  onboardingWebhook?: string;
  onboardingWebhookAuthentication?: WebhookAuthenticationPreference;
}

export const webhookPreferencesSchema: Schema<WebhookPreferences> = object({
  onboardingWebhook: ['onboardingWebhook', optional(string())],
  onboardingWebhookAuthentication: [
    'onboardingWebhookAuthentication',
    optional(lazy(() => webhookAuthenticationPreferenceSchema)),
  ],
});
