/**
 * Yapstone Staged On-Boarding ServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import { Type2Enum, type2EnumSchema } from './type2Enum';

export interface WebhookAuthenticationPreference {
  /** The authentication mechanism to use when making webhook callbacks to client URLs. */
  type?: Type2Enum;
  /**
   * For a type of AUTHORIZATION_HEADER this value should contain what will be placed into the Authorization header, for each webhook callback. When reading back this preference from a response this value field will contain a masked version of the originally supplied value.
   * For a type of TLS_CLIENT_AUTHENTICATION this value should be left empty, and the server side will populate here the Public Key half in PEM format. This Public Key should then be used by the webhook implementation to authenticate the caller.
   */
  value?: string;
}

export const webhookAuthenticationPreferenceSchema: Schema<WebhookAuthenticationPreference> = object(
  {
    type: ['type', optional(type2EnumSchema)],
    value: ['value', optional(string())],
  }
);
