<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib\Models;

use stdClass;

class WebhookPreferences implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $onboardingWebhook;

    /**
     * @var WebhookAuthenticationPreference|null
     */
    private $onboardingWebhookAuthentication;

    /**
     * Returns Onboarding Webhook.
     * Client supplied URL that will be notified for all onboarding events.
     */
    public function getOnboardingWebhook(): ?string
    {
        return $this->onboardingWebhook;
    }

    /**
     * Sets Onboarding Webhook.
     * Client supplied URL that will be notified for all onboarding events.
     *
     * @maps onboardingWebhook
     */
    public function setOnboardingWebhook(?string $onboardingWebhook): void
    {
        $this->onboardingWebhook = $onboardingWebhook;
    }

    /**
     * Returns Onboarding Webhook Authentication.
     */
    public function getOnboardingWebhookAuthentication(): ?WebhookAuthenticationPreference
    {
        return $this->onboardingWebhookAuthentication;
    }

    /**
     * Sets Onboarding Webhook Authentication.
     *
     * @maps onboardingWebhookAuthentication
     */
    public function setOnboardingWebhookAuthentication(
        ?WebhookAuthenticationPreference $onboardingWebhookAuthentication
    ): void {
        $this->onboardingWebhookAuthentication = $onboardingWebhookAuthentication;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->onboardingWebhook)) {
            $json['onboardingWebhook']               = $this->onboardingWebhook;
        }
        if (isset($this->onboardingWebhookAuthentication)) {
            $json['onboardingWebhookAuthentication'] = $this->onboardingWebhookAuthentication;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
