<?php

declare(strict_types=1);

/*
 * YapstoneStagedOnBoardingServicesLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace YapstoneStagedOnBoardingServicesLib;

use YapstoneStagedOnBoardingServicesLib\Http\HttpRequest;

/**
 * Utility class for authorization and token management.
 */
class CustomHeaderAuthenticationManager implements AuthManagerInterface, CustomHeaderAuthenticationCredentials
{
    private $authorization;

    /**
     * Returns an instance of this class.
     *
     * @param string $authorization
     */
    public function __construct(string $authorization)
    {
        $this->authorization = $authorization;
    }

    /**
     * String value for authorization.
     */
    public function getAuthorization(): string
    {
        return $this->authorization;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $authorization
     */
    public function equals(string $authorization): bool
    {
        return $authorization == $this->authorization;
    }

    /**
     * Adds authentication to the given HttpRequest.
     */
    public function apply(HttpRequest $httpRequest)
    {
        $httpRequest->addHeader('Authorization', $this->authorization);
    }
}
